version: '3.9'

services:
  db:
    image: postgres:13.21-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d

  server:
    build:
      context: ./server
    ports:
      - "5254:8080"
    environment:
      ConnectionString_postgres: "Host=db;Port=5432;Database=gadgetshopdb;Username=postgres;Password=postgres"
      FrontendUrl: "http://localhost:4200"
    depends_on:
      - db

  client:
    build:
      context: ./client
    ports:
      - "4200:8080"
    depends_on:
      - server